site_name: Unofficial ONB Guide Library
theme:
  name: material
plugins:
  - search
  - awesome-pages
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
